---

- name: reload_systemd
  command: /usr/bin/systemctl --system daemon-reload

- name:         restart_seafile
  service:
    name:       '{{ item.name }}'
    state:      restarted
    sleep:      5
  when:         ansible_os_family in item.os_family
  with_items:   SEAFILE_INIT_SCRIPTS

